In [4]:
import numpy as np
import array

In [35]:
maths1 = array.array('i',[85,81,93,90,88])
maths1,type(maths1)

(array('i', [85, 81, 93, 90, 88]), array.array)

In [40]:
[i+5 for i in maths1]

[90, 86, 98, 95, 93]

In [36]:
maths1+5

TypeError: can only append array (not "int") to array

In [37]:
maths = np.array([85,81,93,90,88])
maths

array([85, 81, 93, 90, 88])

In [42]:
maths*5

array([425, 405, 465, 450, 440])

array({10, 20}, dtype=object)

In [16]:
maths1 + maths1

array('i', [85, 81, 93, 90, 88, 85, 81, 93, 90, 88])

In [11]:
type(maths)

numpy.ndarray

In [12]:
maths = np.array([85,81,93,90,88])
physics = np.array([75,79,86,80,89])
chemistry = np.array([81,89,86,75,90])

In [13]:
type(maths),type(physics),type(chemistry)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
maths**2

array([7225, 6561, 8649, 8100, 7744])

In [17]:
total_marks = maths+physics+chemistry
total_marks

array([241, 249, 265, 245, 267])

In [27]:
x = np.array([8,12,34,13,10,6,3,5,15,23,2])

In [20]:
np.sqrt(x),np.square(x)

(array([2.82842712, 3.46410162, 5.83095189, 3.60555128, 3.16227766,
        2.44948974, 1.73205081, 2.23606798, 3.87298335, 4.79583152]),
 array([  64,  144, 1156,  169,  100,   36,    9,   25,  225,  529]))

In [23]:
x**0.5,x**2

(array([2.82842712, 3.46410162, 5.83095189, 3.60555128, 3.16227766,
        2.44948974, 1.73205081, 2.23606798, 3.87298335, 4.79583152]),
 array([  64,  144, 1156,  169,  100,   36,    9,   25,  225,  529]))

In [28]:
np.log10(x),np.log2(x),np.log(x)

(array([0.90308999, 1.07918125, 1.53147892, 1.11394335, 1.        ,
        0.77815125, 0.47712125, 0.69897   , 1.17609126, 1.36172784,
        0.30103   ]),
 array([3.        , 3.5849625 , 5.08746284, 3.70043972, 3.32192809,
        2.5849625 , 1.5849625 , 2.32192809, 3.9068906 , 4.52356196,
        1.        ]),
 array([2.07944154, 2.48490665, 3.52636052, 2.56494936, 2.30258509,
        1.79175947, 1.09861229, 1.60943791, 2.7080502 , 3.13549422,
        0.69314718]))

In [29]:
angles = np.array([0,30,45,60,90])
np.sin(np.radians(angles))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [33]:
np.power(x,3)

array([  512,  1728, 39304,  2197,  1000,   216,    27,   125,  3375,
       12167,     8], dtype=int32)

In [34]:
x**3

array([  512,  1728, 39304,  2197,  1000,   216,    27,   125,  3375,
       12167,     8], dtype=int32)