In [1]:
import numpy as np

In [2]:
maths = np.array([82,88,87,92,90,85,80,81])
maths

array([82, 88, 87, 92, 90, 85, 80, 81])

In [3]:
maths.ndim,maths.shape,maths.dtype,maths.itemsize

(1, (8,), dtype('int32'), 4)

In [5]:
physics = np.array([87,80,76,75,90,94[,92,80])
physics.ndim,physics.shape

(1, (8,))

In [6]:
chemistry = np.array([81,80,77,75,88,90,92,91])
chemistry.ndim,chemistry.shape

(1, (8,))

In [7]:
marks = np.array([[82,88,87,92,90,85,80,81],[87,80,76,75,90,94,92,80],[81,80,77,75,88,90,92,91]])
marks

array([[82, 88, 87, 92, 90, 85, 80, 81],
       [87, 80, 76, 75, 90, 94, 92, 80],
       [81, 80, 77, 75, 88, 90, 92, 91]])

In [9]:
marks.ndim,marks.shape

(2, (3, 8))

In [10]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
x.shape,x.ndim

((6, 3), 2)

In [20]:
y = np.array([[7,4,5,2,1],[8,12,45,23,10],[88,80,81,92,80],[-10,-20,-30,40,60]])
y.shape

(4, 5)

In [23]:
z = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
z.shape,z.ndim,z.dtype,z.itemsize

((5, 2), 2, dtype('int32'), 4)

In [24]:
z = np.array([[1,2,3,4,5],[6,7,8,9,10]])
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
z.shape,z.ndim,z.dtype,z.itemsize

((2, 5), 2, dtype('int32'), 4)