In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x.shape,x.ndim,x.dtype,x.itemsize)

(3, 5) 2 int32 4


In [4]:
y = np.array([[9,15,17,81,21],[7,12,19,55,34],[8,10,13,19,20]])
print(y.ndim,y.shape,y.dtype,y.itemsize)

2 (3, 5) int32 4


In [5]:
z=x+y
print(y)

[[ 9 15 17 81 21]
 [ 7 12 19 55 34]
 [ 8 10 13 19 20]]


In [6]:
z=x-y
print(z)

[[ -8 -13 -14 -77 -16]
 [ -1  -5 -11 -46 -24]
 [  3   2   0  -5  -5]]


In [7]:
z=x*y
print(z)

[[  9  30  51 324 105]
 [ 42  84 152 495 340]
 [ 88 120 169 266 300]]


In [8]:
z=x/y
print(z)

[[0.11111111 0.13333333 0.17647059 0.04938272 0.23809524]
 [0.85714286 0.58333333 0.42105263 0.16363636 0.29411765]
 [1.375      1.2        1.         0.73684211 0.75      ]]


In [9]:
z=x//y
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]]


In [10]:
z=x%y
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 3  2  0 14 15]]


In [11]:
x.shape,y.shape

((3, 5), (3, 5))

In [12]:
print(x.dot(y))

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [15]:
y = np.array([[5,2,3],[6,7,9],[8,9,1],[10,2,4],[6,8,14]])
y,y.shape

(array([[ 5,  2,  3],
        [ 6,  7,  9],
        [ 8,  9,  1],
        [10,  2,  4],
        [ 6,  8, 14]]),
 (5, 3))

In [16]:
print(x.dot(y))

[[111  91 110]
 [286 231 265]
 [461 371 420]]


In [18]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
b = np.arange(1,10)
print(b)

[1 2 3 4 5 6 7 8 9]


In [21]:
c=np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [22]:
d = np.arange(10,0,-1)
print(d)

[10  9  8  7  6  5  4  3  2  1]


In [23]:
i = np.linspace(1,10,10)
print(i)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
j= np.linspace(1,10,20)
print(j)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [25]:
k = np.linspace(1,10,19)
print(k)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [26]:
m= np.linspace(1,10,21)
print(m)

[ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]
