In [1]:
import numpy as np

In [5]:
x = np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [45]:
y  = np.linspace(1,10,20)
y

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [44]:
np.arange(1,10.1,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
y1  = np.linspace(start=1,stop=10,num=10,endpoint=False)
y1

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [16]:
(10-1)/10

0.9

In [19]:
x=np.arange(1,11)
x.shape

(10,)

In [29]:
x_reshape = x.reshape(5,2)
x_reshape,x_reshape.shape,x_reshape.ndim

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]),
 (5, 2),
 2)

In [32]:
x_reshape = x.reshape(2,5)
x_reshape,x_reshape.shape,x_reshape.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 (2, 5),
 2)

In [52]:
y = np.linspace(1,20,24)
y.shape

(24,)

In [36]:
y

array([ 1.        ,  1.82608696,  2.65217391,  3.47826087,  4.30434783,
        5.13043478,  5.95652174,  6.7826087 ,  7.60869565,  8.43478261,
        9.26086957, 10.08695652, 10.91304348, 11.73913043, 12.56521739,
       13.39130435, 14.2173913 , 15.04347826, 15.86956522, 16.69565217,
       17.52173913, 18.34782609, 19.17391304, 20.        ])

In [53]:
I = np.identity(3,dtype='int32')
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
y = y.reshape(8,3)
y

array([[ 1.        ,  1.82608696,  2.65217391],
       [ 3.47826087,  4.30434783,  5.13043478],
       [ 5.95652174,  6.7826087 ,  7.60869565],
       [ 8.43478261,  9.26086957, 10.08695652],
       [10.91304348, 11.73913043, 12.56521739],
       [13.39130435, 14.2173913 , 15.04347826],
       [15.86956522, 16.69565217, 17.52173913],
       [18.34782609, 19.17391304, 20.        ]])

In [55]:
y.dot(I)

array([[ 1.        ,  1.82608696,  2.65217391],
       [ 3.47826087,  4.30434783,  5.13043478],
       [ 5.95652174,  6.7826087 ,  7.60869565],
       [ 8.43478261,  9.26086957, 10.08695652],
       [10.91304348, 11.73913043, 12.56521739],
       [13.39130435, 14.2173913 , 15.04347826],
       [15.86956522, 16.69565217, 17.52173913],
       [18.34782609, 19.17391304, 20.        ]])

In [61]:
x_0 = np.zeros((10,10),dtype='int16')
x_0

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [65]:
x_1 = np.ones((8,5),dtype='int16')
x_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [67]:
y.shape

(8, 3)

In [69]:
np.zeros_like(y,dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
np.ones_like(y,dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [71]:
a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [72]:
b_ones = np.ones((2,5))
b_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
a.dot(b_ones)

array([[ 3.,  3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.,  7.],
       [11., 11., 11., 11., 11.],
       [15., 15., 15., 15., 15.],
       [19., 19., 19., 19., 19.]])

In [74]:
b_ones.dot(a)

array([[25., 30.],
       [25., 30.]])