In [1]:
import numpy as np

In [ ]:
np.random.seed()

In [13]:
np.ones((5,5),dtype='int32')*2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [161]:
np.random.seed(10)
np.random.random_sample((5,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317]])

In [169]:
np.random.seed(20)
np.random.random_sample((5,5))

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959],
       [0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022],
       [0.2723164 , 0.71860593, 0.78300361, 0.85032764, 0.77524489],
       [0.03666431, 0.11669374, 0.7512807 , 0.23921822, 0.25480601],
       [0.85762553, 0.94977903, 0.56168686, 0.17878052, 0.77025193]])

In [163]:
np.random.seed(10)
np.random.random_sample((5,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317]])

In [20]:
np.random.random_sample(10)

array([0.49414624, 0.57161267, 0.5555916 , 0.17164734, 0.27270593,
       0.08019786, 0.61532004, 0.5011595 , 0.23885992, 0.98483175])

In [32]:
10*np.random.random_sample(10)+10

array([14.84367517, 16.26962149, 19.40080641, 17.53230074, 10.2821508 ,
       14.90613051, 14.50530664, 11.85644762, 19.75006262, 13.67604157])

In [95]:
marks = np.random.randint(75,96,(10,5))
marks

array([[81, 92, 76, 87, 87],
       [85, 88, 77, 80, 88],
       [89, 95, 79, 76, 78],
       [82, 87, 89, 83, 85],
       [76, 92, 84, 77, 86],
       [80, 78, 75, 85, 95],
       [94, 76, 80, 79, 80],
       [94, 87, 88, 81, 85],
       [80, 82, 89, 75, 82],
       [89, 85, 92, 75, 79]])

In [97]:
x = np.random.randint(1,20,(4,3))
x

array([[15, 12, 19],
       [ 4, 19, 11],
       [14, 10,  1],
       [ 1, 10,  2]])

In [98]:
y  = np.random.randint(20,50,(3,5))
y

array([[26, 43, 34, 20, 34],
       [36, 37, 37, 42, 24],
       [32, 40, 31, 37, 44]])

In [99]:
x.dot(y)

array([[1430, 1849, 1543, 1507, 1634],
       [1140, 1315, 1180, 1285, 1076],
       [ 756, 1012,  877,  737,  760],
       [ 450,  493,  466,  514,  362]])

In [142]:
x = np.arange(1,16).reshape(3,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
y = np.arange(11,23).reshape(4,3)
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [108]:
y.dot(x)

array([[226, 262, 298, 334, 370],
       [280, 325, 370, 415, 460],
       [334, 388, 442, 496, 550],
       [388, 451, 514, 577, 640]])