In [1]:
import numpy as np

In [2]:
maths = np.array([84,87,90,92,95])
maths.ndim,maths.shape

(1, (5,))

In [3]:
physics = np.array([87,90,91,96,85])
physics.ndim,physics.shape

(1, (5,))

In [4]:
chemistry = np.array([80,83,89,78,79])
chemistry.ndim,chemistry.shape

(1, (5,))

In [5]:
marks = np.array([[84,87,90,92,95],[87,90,91,96,85],[80,83,89,78,79]])
marks.ndim,marks.shape

(2, (3, 5))

In [9]:
marks = np.array([[[[84,87,90,92,95],[87,90,91,96,85],[80,83,89,78,79]],
                 [[80,89,97,67,89],[90,92,90,91,90],[89,78,77,74,79]],
                 [[89,87,80,90,91],[90,89,87,80,95],[80,87,59,90,80]],
                 [[80,88,87,89,89],[91,90,89,78,80],[80,70,89,90,91]]],
                 [[[84,87,90,92,95],[87,90,91,96,85],[80,83,89,78,79]],
                 [[80,89,97,67,89],[90,92,90,91,90],[89,78,77,74,79]],
                 [[89,87,80,90,91],[90,89,87,80,95],[80,87,59,90,80]],
                 [[80,88,87,89,89],[91,90,89,78,80],[80,70,89,90,91]]]])
marks.ndim,marks.shape

(4, (2, 4, 3, 5))

In [10]:
marks

array([[[[84, 87, 90, 92, 95],
         [87, 90, 91, 96, 85],
         [80, 83, 89, 78, 79]],

        [[80, 89, 97, 67, 89],
         [90, 92, 90, 91, 90],
         [89, 78, 77, 74, 79]],

        [[89, 87, 80, 90, 91],
         [90, 89, 87, 80, 95],
         [80, 87, 59, 90, 80]],

        [[80, 88, 87, 89, 89],
         [91, 90, 89, 78, 80],
         [80, 70, 89, 90, 91]]],


       [[[84, 87, 90, 92, 95],
         [87, 90, 91, 96, 85],
         [80, 83, 89, 78, 79]],

        [[80, 89, 97, 67, 89],
         [90, 92, 90, 91, 90],
         [89, 78, 77, 74, 79]],

        [[89, 87, 80, 90, 91],
         [90, 89, 87, 80, 95],
         [80, 87, 59, 90, 80]],

        [[80, 88, 87, 89, 89],
         [91, 90, 89, 78, 80],
         [80, 70, 89, 90, 91]]]])

In [15]:
np.random.randint(70,96,(2,4,3,5))

array([[[[89, 91, 77, 77, 71],
         [76, 81, 87, 76, 73],
         [80, 93, 80, 78, 72]],

        [[80, 83, 87, 95, 84],
         [76, 93, 84, 70, 95],
         [80, 73, 82, 75, 83]],

        [[89, 72, 73, 91, 82],
         [81, 71, 93, 85, 72],
         [72, 76, 73, 84, 79]],

        [[89, 94, 85, 84, 85],
         [85, 82, 82, 78, 78],
         [76, 86, 75, 71, 89]]],


       [[[82, 73, 78, 81, 82],
         [91, 95, 78, 83, 90],
         [83, 70, 89, 80, 89]],

        [[91, 94, 75, 72, 74],
         [92, 78, 71, 80, 71],
         [93, 79, 70, 86, 77]],

        [[72, 80, 75, 75, 71],
         [84, 78, 82, 73, 74],
         [89, 80, 76, 83, 92]],

        [[79, 81, 85, 87, 86],
         [81, 87, 78, 79, 70],
         [79, 86, 74, 86, 87]]]])

In [19]:
np.arange(1,121).reshape(2,4,3,5)

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15]],

        [[ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45]],

        [[ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100],
         [101, 102, 103, 104, 105]],

        [[106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])