In [1]:
import numpy as np

In [43]:
np.random.seed(10)
marks = np.random.randint(70,96,12)
marks

array([79, 74, 85, 70, 87, 95, 86, 87, 78, 79, 70, 80])

In [44]:
marks[:5]

array([79, 74, 85, 70, 87])

In [45]:
marks[-5:]

array([87, 78, 79, 70, 80])

In [46]:
marks[::-1]

array([80, 70, 79, 78, 87, 86, 95, 87, 70, 85, 74, 79])

In [47]:
marks[::2]

array([79, 85, 87, 86, 78, 70])

In [49]:
np.random.seed(10)
marks = np.random.randint(70,96,(5,12))
marks

array([[79, 74, 85, 70, 87, 95, 86, 87, 78, 79, 70, 80],
       [78, 92, 74, 89, 86, 74, 85, 81, 92, 94, 81, 71],
       [78, 74, 84, 87, 89, 92, 83, 75, 83, 89, 95, 83],
       [92, 95, 82, 71, 95, 74, 88, 83, 92, 93, 94, 81],
       [80, 94, 79, 85, 88, 86, 92, 77, 94, 81, 87, 84]])

In [53]:
marks[:3,:5]

array([[79, 74, 85, 70, 87],
       [78, 92, 74, 89, 86],
       [78, 74, 84, 87, 89]])

In [54]:
marks[:,-5:]

array([[87, 78, 79, 70, 80],
       [81, 92, 94, 81, 71],
       [75, 83, 89, 95, 83],
       [83, 92, 93, 94, 81],
       [77, 94, 81, 87, 84]])

In [55]:
marks[-3:,4:9]

array([[89, 92, 83, 75, 83],
       [95, 74, 88, 83, 92],
       [88, 86, 92, 77, 94]])

In [57]:
marks[::-1,::-1]

array([[84, 87, 81, 94, 77, 92, 86, 88, 85, 79, 94, 80],
       [81, 94, 93, 92, 83, 88, 74, 95, 71, 82, 95, 92],
       [83, 95, 89, 83, 75, 83, 92, 89, 87, 84, 74, 78],
       [71, 81, 94, 92, 81, 85, 74, 86, 89, 74, 92, 78],
       [80, 70, 79, 78, 87, 86, 95, 87, 70, 85, 74, 79]])

In [58]:
marks[::2,::3]

array([[79, 70, 86, 79],
       [78, 87, 83, 89],
       [80, 85, 92, 81]])

In [59]:
np.random.seed(10)
marks = np.random.randint(70,96,(4,5,12))
marks

array([[[79, 74, 85, 70, 87, 95, 86, 87, 78, 79, 70, 80],
        [78, 92, 74, 89, 86, 74, 85, 81, 92, 94, 81, 71],
        [78, 74, 84, 87, 89, 92, 83, 75, 83, 89, 95, 83],
        [92, 95, 82, 71, 95, 74, 88, 83, 92, 93, 94, 81],
        [80, 94, 79, 85, 88, 86, 92, 77, 94, 81, 87, 84]],

       [[77, 81, 71, 90, 70, 94, 82, 75, 74, 77, 94, 94],
        [88, 82, 92, 72, 78, 85, 83, 94, 85, 76, 92, 91],
        [80, 92, 81, 86, 82, 70, 92, 95, 87, 85, 82, 78],
        [80, 83, 95, 81, 71, 88, 83, 78, 95, 79, 75, 70],
        [88, 93, 73, 86, 90, 88, 86, 84, 89, 85, 89, 87]],

       [[88, 91, 95, 84, 86, 80, 87, 70, 87, 79, 86, 79],
        [82, 88, 87, 87, 86, 70, 75, 79, 70, 90, 76, 92],
        [70, 72, 73, 73, 88, 92, 83, 81, 86, 91, 83, 81],
        [87, 89, 92, 75, 81, 91, 71, 81, 94, 70, 75, 79],
        [78, 75, 81, 81, 77, 78, 91, 78, 83, 95, 95, 84]],

       [[87, 91, 83, 79, 71, 74, 93, 77, 77, 79, 77, 92],
        [70, 73, 79, 90, 82, 74, 76, 84, 94, 90, 80, 79],
        

In [62]:
marks[2,-3:,:5]

array([[70, 72, 73, 73, 88],
       [87, 89, 92, 75, 81],
       [78, 75, 81, 81, 77]])

In [67]:
marks[1::2,::2,::-2]

array([[[94, 77, 75, 94, 90, 81],
        [78, 85, 95, 70, 86, 92],
        [87, 85, 84, 88, 86, 93]],

       [[92, 79, 77, 74, 79, 91],
        [90, 75, 81, 80, 76, 71],
        [77, 77, 89, 83, 71, 86]]])

In [70]:
marks[:,0,-5:]

array([[87, 78, 79, 70, 80],
       [75, 74, 77, 94, 94],
       [70, 87, 79, 86, 79],
       [77, 77, 79, 77, 92]])

In [74]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [77]:
x.transpose().shape

(5, 2)

In [79]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
np.linspace(1,10,21).reshape(7,3)

array([[ 1.  ,  1.45,  1.9 ],
       [ 2.35,  2.8 ,  3.25],
       [ 3.7 ,  4.15,  4.6 ],
       [ 5.05,  5.5 ,  5.95],
       [ 6.4 ,  6.85,  7.3 ],
       [ 7.75,  8.2 ,  8.65],
       [ 9.1 ,  9.55, 10.  ]])

In [87]:
np.random.random_sample((2,10,4))

array([[[0.80356835, 0.3512135 , 0.09344038, 0.81331608],
        [0.78486672, 0.39341911, 0.86447919, 0.38403077],
        [0.25730289, 0.82940192, 0.7363827 , 0.50760091],
        [0.64432662, 0.21318657, 0.89570895, 0.96594625],
        [0.31700156, 0.86555262, 0.31028371, 0.02526395],
        [0.04919516, 0.18462684, 0.06903334, 0.25747542],
        [0.91358173, 0.45784951, 0.13021179, 0.80989167],
        [0.40346984, 0.02443264, 0.85683104, 0.27429482],
        [0.70910596, 0.35577234, 0.79430906, 0.84461886],
        [0.53814752, 0.55908652, 0.12250998, 0.37764192]],

       [[0.42874733, 0.51120865, 0.89176257, 0.30021061],
        [0.39644188, 0.79327323, 0.41227608, 0.18486755],
        [0.84024732, 0.5692714 , 0.06005021, 0.98891697],
        [0.22878233, 0.61470171, 0.36802668, 0.80277594],
        [0.62756185, 0.82121648, 0.28825314, 0.27479513],
        [0.60105189, 0.9385142 , 0.70729631, 0.26340316],
        [0.12233592, 0.45872423, 0.9748125 , 0.68057437],
        [0.1

In [89]:
m1 = np.matrix('1 2 3 4;5 6 7 8;9 10 11 12')
m1

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [93]:
m2 = np.matrix('1 2;3 4;5 6; 7 8')
m2

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [94]:
m1*m2

matrix([[ 50,  60],
        [114, 140],
        [178, 220]])